[2024-05-27T00:21:09.051+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T00:21:09.069+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_python_operator_v05.get_name scheduled__2024-05-23T00:00:00+00:00 [queued]>
[2024-05-27T00:21:09.076+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_python_operator_v05.get_name scheduled__2024-05-23T00:00:00+00:00 [queued]>
[2024-05-27T00:21:09.076+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-27T00:21:09.094+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_name> on 2024-05-23 00:00:00+00:00
[2024-05-27T00:21:09.099+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11801) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-27T00:21:09.100+0000] {standard_task_runner.py:63} INFO - Started process 11805 to run task
[2024-05-27T00:21:09.099+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_python_operator_v05', 'get_name', 'scheduled__2024-05-23T00:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_python_operator_2.py', '--cfg-path', '/tmp/tmpyligaayu']
[2024-05-27T00:21:09.101+0000] {standard_task_runner.py:91} INFO - Job 177: Subtask get_name
[2024-05-27T00:21:09.130+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_python_operator_v05.get_name scheduled__2024-05-23T00:00:00+00:00 [running]> on host 6bbd6353fbe6
[2024-05-27T00:21:09.176+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gauti' AIRFLOW_CTX_DAG_ID='dag_python_operator_v05' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-23T00:00:00+00:00'
[2024-05-27T00:21:09.177+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T00:21:09.189+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T00:21:09.191+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_dag_python_operator_2.py", line 22, in get_name
    ti.xcom_push(key='last_name', vlaue='swamy')
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_push() got an unexpected keyword argument 'vlaue'
[2024-05-27T00:21:09.195+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_python_operator_v05, task_id=get_name, run_id=scheduled__2024-05-23T00:00:00+00:00, execution_date=20240523T000000, start_date=20240527T002109, end_date=20240527T002109
[2024-05-27T00:21:09.203+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 177 for task get_name (TaskInstance.xcom_push() got an unexpected keyword argument 'vlaue'; 11805)
[2024-05-27T00:21:09.239+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-27T00:21:09.250+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-27T00:21:09.250+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
