[2024-05-25T14:12:46.798+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T14:12:46.821+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_python_operator_v04.greet scheduled__2024-05-24T00:00:00+00:00 [queued]>
[2024-05-25T14:12:46.826+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_python_operator_v04.greet scheduled__2024-05-24T00:00:00+00:00 [queued]>
[2024-05-25T14:12:46.826+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-05-25T14:12:46.833+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): greet> on 2024-05-24 00:00:00+00:00
[2024-05-25T14:12:46.838+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7121) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-25T14:12:46.839+0000] {standard_task_runner.py:63} INFO - Started process 7124 to run task
[2024-05-25T14:12:46.837+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_python_operator_v04', 'greet', 'scheduled__2024-05-24T00:00:00+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_python_operator_2.py', '--cfg-path', '/tmp/tmp36wxetru']
[2024-05-25T14:12:46.840+0000] {standard_task_runner.py:91} INFO - Job 170: Subtask greet
[2024-05-25T14:12:46.862+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_python_operator_v04.greet scheduled__2024-05-24T00:00:00+00:00 [running]> on host 6bbd6353fbe6
[2024-05-25T14:12:46.899+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gauti' AIRFLOW_CTX_DAG_ID='dag_python_operator_v04' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-24T00:00:00+00:00'
[2024-05-25T14:12:46.900+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T14:12:46.906+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T14:12:46.906+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/create_dag_python_operator_2.py", line 14, in greet
    name = ti.xcoms_pull(task_ids='get_name')
           ^^^^^^^^^^^^^
AttributeError: 'TaskInstance' object has no attribute 'xcoms_pull'. Did you mean: 'xcom_pull'?
[2024-05-25T14:12:46.912+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_python_operator_v04, task_id=greet, run_id=scheduled__2024-05-24T00:00:00+00:00, execution_date=20240524T000000, start_date=20240525T141246, end_date=20240525T141246
[2024-05-25T14:12:46.917+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 170 for task greet ('TaskInstance' object has no attribute 'xcoms_pull'; 7124)
[2024-05-25T14:12:46.939+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T14:12:46.946+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T14:12:46.947+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
