[2024-05-27T00:41:35.351+0000] {processor.py:161} INFO - Started process (PID=12977) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:41:35.351+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:41:35.352+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:41:35.352+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:41:35.357+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:41:35.355+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 8, in <module>
    'retry_delay': timedelta(minutes=5)
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-05-27T00:41:35.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:41:35.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.022 seconds
[2024-05-27T00:42:05.751+0000] {processor.py:161} INFO - Started process (PID=13003) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:42:05.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:42:05.753+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:42:05.753+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:42:05.761+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:42:05.758+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 8, in <module>
    'retry_delay': timedelta(minutes=5)
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-05-27T00:42:05.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:42:05.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:42:36.159+0000] {processor.py:161} INFO - Started process (PID=13029) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:42:36.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:42:36.161+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:42:36.161+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:42:36.170+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:42:36.165+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 8, in <module>
    'retry_delay': timedelta(minutes=5)
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-05-27T00:42:36.172+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:42:36.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.033 seconds
[2024-05-27T00:43:06.533+0000] {processor.py:161} INFO - Started process (PID=13055) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:06.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:43:06.535+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:06.534+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:06.542+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:06.539+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 8, in <module>
    'retry_delay': timedelta(minutes=5)
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-05-27T00:43:06.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:06.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:43:07.574+0000] {processor.py:161} INFO - Started process (PID=13060) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:07.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:43:07.577+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:07.576+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:07.583+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:07.582+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 1, in <module>
    from datetime import datetime, de
ImportError: cannot import name 'de' from 'datetime' (/usr/local/lib/python3.12/datetime.py)
[2024-05-27T00:43:07.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:07.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:43:09.611+0000] {processor.py:161} INFO - Started process (PID=13065) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:09.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:43:09.614+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:09.613+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:09.622+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:09.621+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 1, in <module>
    from datetime import datetime, delta
ImportError: cannot import name 'delta' from 'datetime' (/usr/local/lib/python3.12/datetime.py)
[2024-05-27T00:43:09.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:09.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.034 seconds
[2024-05-27T00:43:14.703+0000] {processor.py:161} INFO - Started process (PID=13070) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:14.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:43:14.705+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:14.705+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:14.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:14.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:43:37.021+0000] {processor.py:161} INFO - Started process (PID=13096) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:37.022+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:43:37.023+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:37.023+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:37.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:37.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:43:41.080+0000] {processor.py:161} INFO - Started process (PID=13101) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:41.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:43:41.082+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:41.082+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:41.088+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:41.087+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 11
    @dag()
SyntaxError: invalid syntax
[2024-05-27T00:43:41.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:41.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:43:48.145+0000] {processor.py:161} INFO - Started process (PID=13112) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:48.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:43:48.148+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:48.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:48.153+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:48.152+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 12
    def hello_world
                   ^
SyntaxError: expected '('
[2024-05-27T00:43:48.154+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:48.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:43:50.201+0000] {processor.py:161} INFO - Started process (PID=13117) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:50.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:43:50.203+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:50.203+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:50.207+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:50.206+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 12
    def hello_world_etl
                       ^
SyntaxError: expected '('
[2024-05-27T00:43:50.207+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:50.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.026 seconds
[2024-05-27T00:43:52.235+0000] {processor.py:161} INFO - Started process (PID=13122) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:52.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:43:52.237+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:52.237+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:52.242+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:52.241+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 12
    def hello_world_etl()
                         ^
SyntaxError: expected ':'
[2024-05-27T00:43:52.243+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:52.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.026 seconds
[2024-05-27T00:43:53.278+0000] {processor.py:161} INFO - Started process (PID=13127) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:53.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:43:53.280+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:53.280+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:53.285+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:53.284+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 13
    
    ^
IndentationError: expected an indented block after function definition on line 12
[2024-05-27T00:43:53.286+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:53.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:43:55.319+0000] {processor.py:161} INFO - Started process (PID=13132) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:55.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:43:55.321+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:55.321+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:55.327+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:55.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:43:57.348+0000] {processor.py:161} INFO - Started process (PID=13137) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:57.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:43:57.349+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:43:57.349+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:57.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:43:57.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.012 seconds
[2024-05-27T00:44:22.680+0000] {processor.py:161} INFO - Started process (PID=13163) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:22.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:44:22.683+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:44:22.683+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:22.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:22.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.026 seconds
[2024-05-27T00:44:24.720+0000] {processor.py:161} INFO - Started process (PID=13168) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:24.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:44:24.722+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:44:24.722+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:24.729+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:44:24.727+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 11, in <module>
    @dag(dag_id)
         ^^^^^^
NameError: name 'dag_id' is not defined
[2024-05-27T00:44:24.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:24.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.034 seconds
[2024-05-27T00:44:33.846+0000] {processor.py:161} INFO - Started process (PID=13178) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:33.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:44:33.848+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:44:33.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:33.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:33.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.024 seconds
[2024-05-27T00:44:37.963+0000] {processor.py:161} INFO - Started process (PID=13193) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:37.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:44:37.966+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:44:37.965+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:37.972+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:37.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:44:40.003+0000] {processor.py:161} INFO - Started process (PID=13198) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:40.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:44:40.006+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:44:40.005+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:40.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:40.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.026 seconds
[2024-05-27T00:44:58.234+0000] {processor.py:161} INFO - Started process (PID=13209) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:58.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:44:58.236+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:44:58.236+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:58.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:44:58.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.029 seconds
[2024-05-27T00:45:02.320+0000] {processor.py:161} INFO - Started process (PID=13219) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:02.321+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:02.323+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:02.322+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:02.328+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:02.327+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 13
    def
    ^^^
SyntaxError: invalid syntax
[2024-05-27T00:45:02.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:02.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:45:06.414+0000] {processor.py:161} INFO - Started process (PID=13234) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:06.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:06.416+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:06.416+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:06.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:06.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.028 seconds
[2024-05-27T00:45:08.445+0000] {processor.py:161} INFO - Started process (PID=13239) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:08.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:08.447+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:08.447+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:08.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:08.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.025 seconds
[2024-05-27T00:45:11.515+0000] {processor.py:161} INFO - Started process (PID=13244) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:11.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:11.519+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:11.518+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:11.525+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:11.523+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 15
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-05-27T00:45:11.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:11.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.040 seconds
[2024-05-27T00:45:19.624+0000] {processor.py:161} INFO - Started process (PID=13255) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:19.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:19.627+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:19.627+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:19.632+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:19.631+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 15
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-05-27T00:45:19.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:19.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.031 seconds
[2024-05-27T00:45:22.679+0000] {processor.py:161} INFO - Started process (PID=13260) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:22.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:22.684+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:22.683+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:22.689+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:22.688+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 15
    )
    ^
SyntaxError: positional argument follows keyword argument
[2024-05-27T00:45:22.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:22.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:45:26.743+0000] {processor.py:161} INFO - Started process (PID=13265) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:26.745+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:26.746+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:26.746+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:26.753+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:26.752+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 14, in <module>
    start_date=da
               ^^
NameError: name 'da' is not defined
[2024-05-27T00:45:26.754+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:26.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:45:30.808+0000] {processor.py:161} INFO - Started process (PID=13275) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:30.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:30.809+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:30.809+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:30.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:30.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.012 seconds
[2024-05-27T00:45:33.859+0000] {processor.py:161} INFO - Started process (PID=13280) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:33.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:33.861+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:33.861+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:33.869+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:33.868+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 14, in <module>
    start_date=datetime()
               ^^^^^^^^^^
TypeError: function missing required argument 'year' (pos 1)
[2024-05-27T00:45:33.870+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:33.886+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.034 seconds
[2024-05-27T00:45:48.025+0000] {processor.py:161} INFO - Started process (PID=13301) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:48.026+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:48.027+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:48.026+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:48.031+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:48.030+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 14, in <module>
    start_date=datetime(2024, 20)
               ^^^^^^^^^^^^^^^^^^
TypeError: function missing required argument 'day' (pos 3)
[2024-05-27T00:45:48.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:48.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.019 seconds
[2024-05-27T00:45:50.084+0000] {processor.py:161} INFO - Started process (PID=13306) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:50.086+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:50.087+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:50.086+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:50.093+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:50.092+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 14, in <module>
    start_date=datetime(2024, )
               ^^^^^^^^^^^^^^^^
TypeError: function missing required argument 'month' (pos 2)
[2024-05-27T00:45:50.094+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:50.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:45:52.125+0000] {processor.py:161} INFO - Started process (PID=13311) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:52.126+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:52.127+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:52.127+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:52.132+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:52.131+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 14, in <module>
    start_date=datetime(2024, 5, )
               ^^^^^^^^^^^^^^^^^^^
TypeError: function missing required argument 'day' (pos 3)
[2024-05-27T00:45:52.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:52.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.026 seconds
[2024-05-27T00:45:53.160+0000] {processor.py:161} INFO - Started process (PID=13316) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:53.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:45:53.162+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:45:53.162+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:53.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:45:53.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.025 seconds
[2024-05-27T00:46:03.364+0000] {processor.py:161} INFO - Started process (PID=13326) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:46:03.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:46:03.366+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:46:03.366+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:46:03.371+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:46:03.370+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 15
    schedule=
    ^^^^^^^^^
SyntaxError: expected argument value expression
[2024-05-27T00:46:03.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:46:03.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.031 seconds
[2024-05-27T00:46:08.455+0000] {processor.py:161} INFO - Started process (PID=13341) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:46:08.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:46:08.457+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:46:08.457+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:46:08.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:46:08.476+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:46:38.834+0000] {processor.py:161} INFO - Started process (PID=13366) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:46:38.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:46:38.837+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:46:38.837+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:46:38.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:46:38.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.028 seconds
[2024-05-27T00:47:09.199+0000] {processor.py:161} INFO - Started process (PID=13392) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:09.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:09.201+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:09.201+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:09.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:09.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.025 seconds
[2024-05-27T00:47:17.304+0000] {processor.py:161} INFO - Started process (PID=13397) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:17.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:17.307+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:17.306+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:17.313+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:17.311+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 19
    
    ^
IndentationError: expected an indented block after function definition on line 17
[2024-05-27T00:47:17.314+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:17.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.037 seconds
[2024-05-27T00:47:20.349+0000] {processor.py:161} INFO - Started process (PID=13408) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:20.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:20.351+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:20.351+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:20.357+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:20.356+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 19
    @task()
           ^
IndentationError: unexpected unindent
[2024-05-27T00:47:20.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:20.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:47:23.416+0000] {processor.py:161} INFO - Started process (PID=13413) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:23.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:23.419+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:23.418+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:23.424+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:23.423+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 19
    @task():
           ^
SyntaxError: invalid syntax
[2024-05-27T00:47:23.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:23.439+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.029 seconds
[2024-05-27T00:47:27.472+0000] {processor.py:161} INFO - Started process (PID=13418) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:27.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:27.475+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:27.474+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:27.480+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:27.479+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 19
    @task():
           ^
SyntaxError: invalid syntax
[2024-05-27T00:47:27.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:27.495+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:47:30.518+0000] {processor.py:161} INFO - Started process (PID=13423) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:30.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:30.521+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:30.521+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:30.527+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:30.526+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 19
    @task():
           ^
SyntaxError: invalid syntax
[2024-05-27T00:47:30.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:30.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:47:32.593+0000] {processor.py:161} INFO - Started process (PID=13433) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:32.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:32.596+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:32.595+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:32.600+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:32.599+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 19
    @task():
           ^
SyntaxError: invalid syntax
[2024-05-27T00:47:32.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:32.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:47:37.757+0000] {processor.py:161} INFO - Started process (PID=13448) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:37.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:37.760+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:37.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:37.765+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:37.764+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 20
    def get_name():
                   ^
IndentationError: expected an indented block after function definition on line 20
[2024-05-27T00:47:37.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:37.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.033 seconds
[2024-05-27T00:47:42.807+0000] {processor.py:161} INFO - Started process (PID=13453) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:42.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:42.809+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:42.809+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:42.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:42.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.031 seconds
[2024-05-27T00:47:46.881+0000] {processor.py:161} INFO - Started process (PID=13458) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:46.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:46.883+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:46.883+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:46.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:46.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.028 seconds
[2024-05-27T00:47:48.911+0000] {processor.py:161} INFO - Started process (PID=13469) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:48.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:48.913+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:48.913+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:48.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:48.927+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.021 seconds
[2024-05-27T00:47:51.971+0000] {processor.py:161} INFO - Started process (PID=13474) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:51.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:51.974+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:51.973+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:51.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:51.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:47:53.000+0000] {processor.py:161} INFO - Started process (PID=13479) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:53.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:53.003+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:53.002+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:53.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:53.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:47:56.064+0000] {processor.py:161} INFO - Started process (PID=13484) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:56.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:56.067+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:56.067+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:56.073+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:56.072+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 23
    @task()
           ^
IndentationError: unexpected unindent
[2024-05-27T00:47:56.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:56.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:47:59.105+0000] {processor.py:161} INFO - Started process (PID=13489) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:59.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:47:59.107+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:59.107+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:59.112+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:47:59.111+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 24
    def 
        ^
SyntaxError: invalid syntax
[2024-05-27T00:47:59.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:47:59.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:48:02.183+0000] {processor.py:161} INFO - Started process (PID=13494) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:02.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:02.185+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:02.185+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:02.190+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:02.189+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 24
    def get_age()
                 ^
SyntaxError: expected ':'
[2024-05-27T00:48:02.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:02.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:48:05.265+0000] {processor.py:161} INFO - Started process (PID=13504) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:05.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:05.267+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:05.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:05.273+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:05.272+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 25
    
    ^
IndentationError: expected an indented block after function definition on line 24
[2024-05-27T00:48:05.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:05.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.031 seconds
[2024-05-27T00:48:08.335+0000] {processor.py:161} INFO - Started process (PID=13519) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:08.337+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:08.338+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:08.337+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:08.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:08.356+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:48:10.368+0000] {processor.py:161} INFO - Started process (PID=13524) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:10.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:10.371+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:10.370+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:10.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:10.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:48:13.431+0000] {processor.py:161} INFO - Started process (PID=13529) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:13.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:13.434+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:13.433+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:13.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:13.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:48:16.476+0000] {processor.py:161} INFO - Started process (PID=13534) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:16.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:16.479+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:16.478+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:16.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:16.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.028 seconds
[2024-05-27T00:48:20.551+0000] {processor.py:161} INFO - Started process (PID=13545) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:20.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:20.553+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:20.553+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:20.559+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:20.558+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 27
    @task()
           ^
IndentationError: unexpected unindent
[2024-05-27T00:48:20.560+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:20.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.035 seconds
[2024-05-27T00:48:22.586+0000] {processor.py:161} INFO - Started process (PID=13550) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:22.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:22.589+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:22.589+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:22.594+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:22.593+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 28
    def
       ^
SyntaxError: invalid syntax
[2024-05-27T00:48:22.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:22.607+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:48:25.660+0000] {processor.py:161} INFO - Started process (PID=13555) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:25.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:25.663+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:25.662+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:25.668+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:25.667+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 28
    def greet()
               ^
SyntaxError: expected ':'
[2024-05-27T00:48:25.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:25.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.029 seconds
[2024-05-27T00:48:28.706+0000] {processor.py:161} INFO - Started process (PID=13560) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:28.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:28.708+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:28.708+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:28.714+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:28.713+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 28
    def greet(name, age)
                        ^
SyntaxError: expected ':'
[2024-05-27T00:48:28.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:28.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:48:31.770+0000] {processor.py:161} INFO - Started process (PID=13565) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:31.772+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:31.773+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:31.773+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:31.779+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:31.778+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 29
    
    ^
IndentationError: expected an indented block after function definition on line 28
[2024-05-27T00:48:31.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:31.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.031 seconds
[2024-05-27T00:48:34.848+0000] {processor.py:161} INFO - Started process (PID=13575) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:34.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:34.850+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:34.849+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:34.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:34.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.020 seconds
[2024-05-27T00:48:36.879+0000] {processor.py:161} INFO - Started process (PID=13580) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:36.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:36.881+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:36.880+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:36.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:36.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.026 seconds
[2024-05-27T00:48:40.963+0000] {processor.py:161} INFO - Started process (PID=13595) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:40.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:48:40.965+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:48:40.965+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:40.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:48:40.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:49:01.230+0000] {processor.py:161} INFO - Started process (PID=13606) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:01.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:49:01.233+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:49:01.233+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:01.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:01.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:49:04.231+0000] {processor.py:161} INFO - Started process (PID=13616) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:04.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:49:04.233+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:49:04.232+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:04.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:04.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.018 seconds
[2024-05-27T00:49:13.346+0000] {processor.py:161} INFO - Started process (PID=13631) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:13.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:49:13.349+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:49:13.348+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:13.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:13.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.028 seconds
[2024-05-27T00:49:16.417+0000] {processor.py:161} INFO - Started process (PID=13636) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:16.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:49:16.420+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:49:16.419+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:16.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:16.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:49:17.439+0000] {processor.py:161} INFO - Started process (PID=13641) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:17.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:49:17.441+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:49:17.440+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:17.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:17.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:49:19.488+0000] {processor.py:161} INFO - Started process (PID=13652) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:19.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:49:19.490+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:49:19.490+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:19.495+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:19.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.021 seconds
[2024-05-27T00:49:22.540+0000] {processor.py:161} INFO - Started process (PID=13657) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:22.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:49:22.542+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:49:22.542+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:22.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:22.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.026 seconds
[2024-05-27T00:49:25.583+0000] {processor.py:161} INFO - Started process (PID=13662) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:25.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:49:25.586+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:49:25.585+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:25.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:25.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:49:27.624+0000] {processor.py:161} INFO - Started process (PID=13667) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:27.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:49:27.627+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:49:27.626+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:27.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:27.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:49:35.747+0000] {processor.py:161} INFO - Started process (PID=13677) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:35.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:49:35.749+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:49:35.749+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:35.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:35.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.026 seconds
[2024-05-27T00:49:37.773+0000] {processor.py:161} INFO - Started process (PID=13682) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:37.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:49:37.776+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:49:37.775+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:37.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:37.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.029 seconds
[2024-05-27T00:49:39.838+0000] {processor.py:161} INFO - Started process (PID=13697) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:39.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:49:39.841+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:49:39.840+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:39.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:49:39.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.020 seconds
[2024-05-27T00:50:10.209+0000] {processor.py:161} INFO - Started process (PID=13722) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:10.210+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:10.211+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:10.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:10.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:10.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.020 seconds
[2024-05-27T00:50:18.277+0000] {processor.py:161} INFO - Started process (PID=13733) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:18.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:18.279+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:18.278+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:18.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:18.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.013 seconds
[2024-05-27T00:50:22.330+0000] {processor.py:161} INFO - Started process (PID=13738) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:22.331+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:22.332+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:22.332+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:22.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:22.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:50:25.381+0000] {processor.py:161} INFO - Started process (PID=13743) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:25.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:25.384+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:25.383+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:25.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:25.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:50:28.428+0000] {processor.py:161} INFO - Started process (PID=13748) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:28.429+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:28.430+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:28.430+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:28.436+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:28.435+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 32
    name=
         ^
SyntaxError: invalid syntax
[2024-05-27T00:50:28.437+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:28.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.033 seconds
[2024-05-27T00:50:32.486+0000] {processor.py:161} INFO - Started process (PID=13753) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:32.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:32.488+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:32.488+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:32.493+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:32.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.026 seconds
[2024-05-27T00:50:34.526+0000] {processor.py:161} INFO - Started process (PID=13758) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:34.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:34.529+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:34.529+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:34.535+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:34.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:50:40.675+0000] {processor.py:161} INFO - Started process (PID=13778) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:40.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:40.677+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:40.677+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:40.683+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:40.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.028 seconds
[2024-05-27T00:50:41.690+0000] {processor.py:161} INFO - Started process (PID=13783) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:41.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:41.693+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:41.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:41.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:41.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.028 seconds
[2024-05-27T00:50:46.773+0000] {processor.py:161} INFO - Started process (PID=13788) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:46.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:46.775+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:46.775+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:46.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:46.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:50:47.799+0000] {processor.py:161} INFO - Started process (PID=13793) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:47.800+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:47.801+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:47.801+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:47.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:47.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.026 seconds
[2024-05-27T00:50:49.855+0000] {processor.py:161} INFO - Started process (PID=13804) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:49.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:49.857+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:49.857+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:49.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:49.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.029 seconds
[2024-05-27T00:50:55.922+0000] {processor.py:161} INFO - Started process (PID=13809) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:55.924+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:55.925+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:55.924+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:55.930+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:55.929+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 34
    greet(name=name, age)
                        ^
SyntaxError: positional argument follows keyword argument
[2024-05-27T00:50:55.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:55.946+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.031 seconds
[2024-05-27T00:50:57.984+0000] {processor.py:161} INFO - Started process (PID=13814) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:57.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:50:57.986+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:50:57.986+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:57.992+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:50:58.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.029 seconds
[2024-05-27T00:51:07.117+0000] {processor.py:161} INFO - Started process (PID=13824) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:07.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:51:07.119+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:07.119+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:07.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:07.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.035 seconds
[2024-05-27T00:51:10.195+0000] {processor.py:161} INFO - Started process (PID=13829) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:10.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:51:10.197+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:10.197+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:10.204+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:10.201+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 36, in <module>
    greet_dag
NameError: name 'greet_dag' is not defined
[2024-05-27T00:51:10.206+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:10.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.028 seconds
[2024-05-27T00:51:14.282+0000] {processor.py:161} INFO - Started process (PID=13844) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:14.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:51:14.283+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:14.283+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:14.287+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:14.286+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 36, in <module>
    greet_dag = hell
                ^^^^
NameError: name 'hell' is not defined. Did you mean: 'help'?
[2024-05-27T00:51:14.287+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:14.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.019 seconds
[2024-05-27T00:51:15.327+0000] {processor.py:161} INFO - Started process (PID=13849) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:15.329+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:51:15.330+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:15.330+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:15.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:15.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:51:16.356+0000] {processor.py:161} INFO - Started process (PID=13854) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:16.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:51:16.358+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:16.357+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:16.374+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:16.458+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:16.457+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:dag_with_taskflow_api_v01
[2024-05-27T00:51:16.464+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:16.463+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:dag_with_taskflow_api_v01
[2024-05-27T00:51:16.466+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:16.466+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:dag_with_taskflow_api_v01
[2024-05-27T00:51:16.466+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:16.466+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:51:16.472+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:16.472+0000] {dag.py:3118} INFO - Creating ORM DAG for dag_with_taskflow_api_v01
[2024-05-27T00:51:16.477+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:16.477+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-22 00:00:00+00:00, run_after=2024-05-23 00:00:00+00:00
[2024-05-27T00:51:16.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.138 seconds
[2024-05-27T00:51:19.409+0000] {processor.py:161} INFO - Started process (PID=13865) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:19.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:51:19.411+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:19.411+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:19.422+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:19.432+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:19.432+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:51:19.450+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:19.450+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-22 00:00:00+00:00, run_after=2024-05-23 00:00:00+00:00
[2024-05-27T00:51:19.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.062 seconds
[2024-05-27T00:51:49.782+0000] {processor.py:161} INFO - Started process (PID=13920) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:49.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:51:49.784+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:49.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:49.795+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:51:49.811+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:49.811+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:51:49.821+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:51:49.821+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:51:49.828+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.052 seconds
[2024-05-27T00:52:20.114+0000] {processor.py:161} INFO - Started process (PID=13946) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:52:20.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:52:20.117+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:52:20.116+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:52:20.128+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:52:20.147+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:52:20.147+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:52:20.158+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:52:20.158+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:52:20.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.058 seconds
[2024-05-27T00:52:50.434+0000] {processor.py:161} INFO - Started process (PID=13972) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:52:50.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:52:50.435+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:52:50.435+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:52:50.442+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:52:50.458+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:52:50.458+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:52:50.469+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:52:50.469+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:52:50.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.052 seconds
[2024-05-27T00:53:20.784+0000] {processor.py:161} INFO - Started process (PID=13998) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:53:20.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:53:20.785+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:53:20.785+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:53:20.792+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:53:20.810+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:53:20.809+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:53:20.822+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:53:20.822+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:53:20.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.053 seconds
[2024-05-27T00:53:51.164+0000] {processor.py:161} INFO - Started process (PID=14024) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:53:51.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:53:51.167+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:53:51.166+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:53:51.180+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:53:51.202+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:53:51.202+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:53:51.215+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:53:51.215+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:53:51.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.066 seconds
[2024-05-27T00:53:54.203+0000] {processor.py:161} INFO - Started process (PID=14029) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:53:54.204+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:53:54.206+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:53:54.205+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:53:54.218+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:53:54.215+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 36, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 19, in hello_world_etl
    @task(multiple)
          ^^^^^^^^
NameError: name 'multiple' is not defined
[2024-05-27T00:53:54.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:53:54.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.037 seconds
[2024-05-27T00:53:58.245+0000] {processor.py:161} INFO - Started process (PID=14034) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:53:58.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:53:58.247+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:53:58.247+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:53:58.264+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:53:58.258+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 36, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 19, in hello_world_etl
    @task(multiple_outputs)
          ^^^^^^^^^^^^^^^^
NameError: name 'multiple_outputs' is not defined
[2024-05-27T00:53:58.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:53:58.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.041 seconds
[2024-05-27T00:54:02.315+0000] {processor.py:161} INFO - Started process (PID=14039) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:02.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:02.317+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:02.317+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:02.331+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:02.413+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:02.413+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:54:02.424+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:02.424+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:54:02.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.124 seconds
[2024-05-27T00:54:10.412+0000] {processor.py:161} INFO - Started process (PID=14049) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:10.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:10.414+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:10.413+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:10.426+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:10.437+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:10.436+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:54:10.451+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:10.451+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:54:10.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.057 seconds
[2024-05-27T00:54:13.504+0000] {processor.py:161} INFO - Started process (PID=14064) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:13.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:13.506+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:13.506+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:13.519+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:13.529+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:13.528+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:54:13.543+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:13.543+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:54:13.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.056 seconds
[2024-05-27T00:54:17.598+0000] {processor.py:161} INFO - Started process (PID=14069) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:17.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:17.601+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:17.600+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:17.615+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:17.624+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:17.624+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:54:17.637+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:17.637+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:54:17.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.053 seconds
[2024-05-27T00:54:22.665+0000] {processor.py:161} INFO - Started process (PID=14080) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:22.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:22.666+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:22.666+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:22.678+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:22.687+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:22.687+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:54:22.700+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:22.699+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:54:22.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.048 seconds
[2024-05-27T00:54:26.740+0000] {processor.py:161} INFO - Started process (PID=14085) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:26.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:26.742+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:26.742+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:26.747+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:26.746+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 23
    'last_name'
              ^
SyntaxError: ':' expected after dictionary key
[2024-05-27T00:54:26.747+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:26.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.029 seconds
[2024-05-27T00:54:28.765+0000] {processor.py:161} INFO - Started process (PID=14090) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:28.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:28.767+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:28.767+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:28.770+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:28.770+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 23
    'last_name':
               ^
SyntaxError: expression expected after dictionary key and ':'
[2024-05-27T00:54:28.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:28.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.021 seconds
[2024-05-27T00:54:30.815+0000] {processor.py:161} INFO - Started process (PID=14095) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:30.816+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:30.817+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:30.817+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:30.829+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:30.838+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:30.838+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:54:30.851+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:30.851+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:54:30.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.052 seconds
[2024-05-27T00:54:32.851+0000] {processor.py:161} INFO - Started process (PID=14100) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:32.852+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:32.853+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:32.853+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:32.866+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:32.888+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:32.888+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:54:32.900+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:32.899+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:54:32.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.065 seconds
[2024-05-27T00:54:41.003+0000] {processor.py:161} INFO - Started process (PID=14110) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:41.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:41.006+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:41.006+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:41.025+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:41.019+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3157, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2024-05-27T00:54:41.026+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:41.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.043 seconds
[2024-05-27T00:54:44.085+0000] {processor.py:161} INFO - Started process (PID=14125) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:44.086+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:44.087+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:44.087+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:44.101+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:44.097+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3157, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2024-05-27T00:54:44.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:44.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.035 seconds
[2024-05-27T00:54:47.169+0000] {processor.py:161} INFO - Started process (PID=14130) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:47.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:47.172+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:47.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:47.184+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:47.181+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3157, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2024-05-27T00:54:47.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:47.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.042 seconds
[2024-05-27T00:54:54.254+0000] {processor.py:161} INFO - Started process (PID=14141) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:54.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:54.257+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:54.257+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:54.273+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:54.269+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3157, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2024-05-27T00:54:54.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:54.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.039 seconds
[2024-05-27T00:54:58.322+0000] {processor.py:161} INFO - Started process (PID=14146) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:58.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:54:58.323+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:58.323+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:58.337+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:54:58.334+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3157, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2024-05-27T00:54:58.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:54:58.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.035 seconds
[2024-05-27T00:55:01.383+0000] {processor.py:161} INFO - Started process (PID=14151) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:01.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:55:01.386+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:55:01.386+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:01.397+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:55:01.395+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3157, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2024-05-27T00:55:01.398+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:01.417+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.040 seconds
[2024-05-27T00:55:31.750+0000] {processor.py:161} INFO - Started process (PID=14177) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:31.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:55:31.752+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:55:31.752+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:31.763+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:55:31.760+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3157, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'first_name'
[2024-05-27T00:55:31.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:31.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.032 seconds
[2024-05-27T00:55:50.022+0000] {processor.py:161} INFO - Started process (PID=14203) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:50.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:55:50.026+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:55:50.025+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:50.039+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:55:50.036+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(name=name, age=age)
               ^^^^
NameError: name 'name' is not defined
[2024-05-27T00:55:50.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:50.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.040 seconds
[2024-05-27T00:55:58.120+0000] {processor.py:161} INFO - Started process (PID=14208) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:58.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:55:58.123+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:55:58.122+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:58.135+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:55:58.133+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(firstname=name, age=age)
                    ^^^^
NameError: name 'name' is not defined
[2024-05-27T00:55:58.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:58.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.034 seconds
[2024-05-27T00:55:59.141+0000] {processor.py:161} INFO - Started process (PID=14213) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:59.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:55:59.143+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:55:59.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:59.149+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:55:59.147+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37
    greet(first_name=name=name, age=age)
                         ^
SyntaxError: invalid syntax
[2024-05-27T00:55:59.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:55:59.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:56:04.237+0000] {processor.py:161} INFO - Started process (PID=14218) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:04.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:56:04.239+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:04.239+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:04.252+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:04.250+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(first_name=name, age=age)
                     ^^^^
NameError: name 'name' is not defined
[2024-05-27T00:56:04.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:04.267+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.035 seconds
[2024-05-27T00:56:07.290+0000] {processor.py:161} INFO - Started process (PID=14223) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:07.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:56:07.292+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:07.292+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:07.304+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:07.301+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(first_name=name_dict, age=age)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3212, in _bind
    raise TypeError('missing a required argument: {arg!r}'. \
TypeError: missing a required argument: 'last_name'
[2024-05-27T00:56:07.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:07.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:56:13.381+0000] {processor.py:161} INFO - Started process (PID=14233) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:13.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:56:13.383+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:13.382+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:13.392+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:13.390+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(first_name=name_dict['first'], age=age)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3212, in _bind
    raise TypeError('missing a required argument: {arg!r}'. \
TypeError: missing a required argument: 'last_name'
[2024-05-27T00:56:13.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:13.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.027 seconds
[2024-05-27T00:56:16.446+0000] {processor.py:161} INFO - Started process (PID=14248) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:16.447+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:56:16.448+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:16.448+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:16.461+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:16.458+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 39, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(first_name=name_dict['first_name'], age=age)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3212, in _bind
    raise TypeError('missing a required argument: {arg!r}'. \
TypeError: missing a required argument: 'last_name'
[2024-05-27T00:56:16.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:16.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.035 seconds
[2024-05-27T00:56:18.512+0000] {processor.py:161} INFO - Started process (PID=14253) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:18.513+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:56:18.514+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:18.514+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:18.528+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:18.525+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 40, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(first_name=name_dict['first_name'],
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3212, in _bind
    raise TypeError('missing a required argument: {arg!r}'. \
TypeError: missing a required argument: 'last_name'
[2024-05-27T00:56:18.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:18.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.036 seconds
[2024-05-27T00:56:20.545+0000] {processor.py:161} INFO - Started process (PID=14264) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:20.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:56:20.547+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:20.547+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:20.561+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:20.558+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 41, in <module>
    greet_dag = hello_world_etl()
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4081, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 37, in hello_world_etl
    greet(first_name=name_dict['first_name'],
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 372, in __call__
    op = self.operator_class(
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/python.py", line 52, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 484, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 253, in __init__
    signature.bind(*op_args, **op_kwargs)
  File "/usr/local/lib/python3.12/inspect.py", line 3242, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 3212, in _bind
    raise TypeError('missing a required argument: {arg!r}'. \
TypeError: missing a required argument: 'last_name'
[2024-05-27T00:56:20.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:20.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.036 seconds
[2024-05-27T00:56:27.652+0000] {processor.py:161} INFO - Started process (PID=14269) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:27.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:56:27.655+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:27.654+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:27.660+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:27.659+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 38
    last_name
    ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-05-27T00:56:27.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:27.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.033 seconds
[2024-05-27T00:56:30.701+0000] {processor.py:161} INFO - Started process (PID=14274) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:30.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:56:30.703+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:30.703+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:30.709+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:30.708+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 38
    last_name=name_dict['']
              
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-05-27T00:56:30.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:30.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.031 seconds
[2024-05-27T00:56:33.762+0000] {processor.py:161} INFO - Started process (PID=14279) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:33.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:56:33.764+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:33.764+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:33.770+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:33.769+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_taskflow_api.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_taskflow_api.py", line 38
    last_name=name_dict['last_name']
              
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2024-05-27T00:56:33.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:33.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.030 seconds
[2024-05-27T00:56:39.867+0000] {processor.py:161} INFO - Started process (PID=14284) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:39.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:56:39.869+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:39.869+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:39.884+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v01' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:39.950+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:39.950+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:56:39.959+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:39.959+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v01 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:56:39.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.109 seconds
[2024-05-27T00:56:46.054+0000] {processor.py:161} INFO - Started process (PID=14304) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:46.055+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:56:46.056+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:46.056+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:46.068+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:46.125+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:46.124+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:dag_with_taskflow_api_v02
[2024-05-27T00:56:46.129+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:46.129+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:dag_with_taskflow_api_v02
[2024-05-27T00:56:46.131+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:46.131+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:dag_with_taskflow_api_v02
[2024-05-27T00:56:46.131+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:46.131+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:56:46.135+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:46.135+0000] {dag.py:3118} INFO - Creating ORM DAG for dag_with_taskflow_api_v02
[2024-05-27T00:56:46.138+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:46.138+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-22 00:00:00+00:00, run_after=2024-05-23 00:00:00+00:00
[2024-05-27T00:56:46.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.095 seconds
[2024-05-27T00:56:49.115+0000] {processor.py:161} INFO - Started process (PID=14315) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:49.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:56:49.117+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:49.116+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:49.124+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:56:49.132+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:49.132+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:56:49.142+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:56:49.142+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-22 00:00:00+00:00, run_after=2024-05-23 00:00:00+00:00
[2024-05-27T00:56:49.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.038 seconds
[2024-05-27T00:57:19.501+0000] {processor.py:161} INFO - Started process (PID=14341) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:57:19.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:57:19.503+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:57:19.502+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:57:19.510+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:57:19.526+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:57:19.526+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:57:19.536+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:57:19.535+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-22 00:00:00+00:00, run_after=2024-05-23 00:00:00+00:00
[2024-05-27T00:57:19.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.047 seconds
[2024-05-27T00:57:49.902+0000] {processor.py:161} INFO - Started process (PID=14403) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:57:49.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:57:49.905+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:57:49.905+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:57:49.915+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:57:49.935+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:57:49.935+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:57:49.947+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:57:49.947+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:57:49.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.061 seconds
[2024-05-27T00:58:20.306+0000] {processor.py:161} INFO - Started process (PID=14429) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:58:20.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:58:20.307+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:58:20.307+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:58:20.314+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:58:20.333+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:58:20.333+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:58:20.343+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:58:20.343+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:58:20.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.050 seconds
[2024-05-27T00:58:50.670+0000] {processor.py:161} INFO - Started process (PID=14455) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:58:50.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:58:50.673+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:58:50.672+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:58:50.680+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:58:50.696+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:58:50.696+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:58:50.708+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:58:50.708+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:58:50.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.052 seconds
[2024-05-27T00:59:21.084+0000] {processor.py:161} INFO - Started process (PID=14480) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:59:21.085+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:59:21.086+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:59:21.086+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:59:21.094+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:59:21.110+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:59:21.110+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:59:21.121+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:59:21.121+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:59:21.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.052 seconds
[2024-05-27T00:59:51.483+0000] {processor.py:161} INFO - Started process (PID=14506) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:59:51.485+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T00:59:51.485+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:59:51.485+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:59:51.494+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T00:59:51.512+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:59:51.511+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T00:59:51.524+0000] {logging_mixin.py:188} INFO - [2024-05-27T00:59:51.524+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T00:59:51.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.055 seconds
[2024-05-27T01:00:21.845+0000] {processor.py:161} INFO - Started process (PID=14532) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:00:21.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T01:00:21.848+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:00:21.847+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:00:21.860+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:00:21.879+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:00:21.878+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T01:00:21.889+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:00:21.889+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T01:00:21.896+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.057 seconds
[2024-05-27T01:00:52.222+0000] {processor.py:161} INFO - Started process (PID=14558) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:00:52.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T01:00:52.223+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:00:52.223+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:00:52.233+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:00:52.250+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:00:52.249+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T01:00:52.259+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:00:52.259+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T01:00:52.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.049 seconds
[2024-05-27T01:01:22.647+0000] {processor.py:161} INFO - Started process (PID=14584) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:01:22.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T01:01:22.649+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:01:22.649+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:01:22.661+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:01:22.680+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:01:22.680+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T01:01:22.690+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:01:22.690+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T01:01:22.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.057 seconds
[2024-05-27T01:01:53.118+0000] {processor.py:161} INFO - Started process (PID=14610) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:01:53.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T01:01:53.120+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:01:53.120+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:01:53.131+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:01:53.149+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:01:53.149+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T01:01:53.159+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:01:53.159+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T01:01:53.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.056 seconds
[2024-05-27T01:02:23.525+0000] {processor.py:161} INFO - Started process (PID=14636) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:02:23.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T01:02:23.527+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:02:23.527+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:02:23.537+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:02:23.555+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:02:23.555+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T01:02:23.565+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:02:23.565+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T01:02:23.572+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.054 seconds
[2024-05-27T01:02:53.922+0000] {processor.py:161} INFO - Started process (PID=14662) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:02:53.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T01:02:53.924+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:02:53.924+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:02:53.935+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:02:53.955+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:02:53.954+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T01:02:53.966+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:02:53.965+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T01:02:53.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.058 seconds
[2024-05-27T01:03:24.284+0000] {processor.py:161} INFO - Started process (PID=14688) to work on /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:03:24.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_taskflow_api.py for tasks to queue
[2024-05-27T01:03:24.286+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:03:24.286+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:03:24.294+0000] {processor.py:840} INFO - DAG(s) 'dag_with_taskflow_api_v02' retrieved from /opt/airflow/dags/dag_with_taskflow_api.py
[2024-05-27T01:03:24.305+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:03:24.305+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-27T01:03:24.313+0000] {logging_mixin.py:188} INFO - [2024-05-27T01:03:24.313+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_with_taskflow_api_v02 to 2024-05-27 00:00:00+00:00, run_after=2024-05-28 00:00:00+00:00
[2024-05-27T01:03:24.320+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_taskflow_api.py took 0.041 seconds
